### ISSUE TITLE
initial feedback from test of chrisbecke/glusterfs-volume from dockerhub

### ISSUE THREAD

**Issue by scyto** [chrisbecke/glusterfs-volume#1]
Hi,

Thanks for putting the version up in the docker registry.

To install i did the following
```
sudo docker plugin install --alias gluster-vol1 chrisbecke/glusterfs-volume GFS_VOLUME=gluster-vol1 GFS_SERVERS=docker01.mydomain.com,docker02.mydomain.com,mydomain.alexbal.com
```
I tested by changing a pre-existing stack to use this driver.  This is the stack for reference. Its my most complex one  and the one where it doesn't matter if the data gets lost :-)  i left old mounts in but commented out for reference. to be clear i didn't copy data over from old location to new location

```
version: "3"
services:
  up_influxdb:
#    container_name: up_influxdb
#    restart: unless-stopped
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
#      - /mnt/iscsi/docker/up_influxdb:/var/lib/influxdb
      - data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=unifi
      - INFLUXDB_ADMIN_USER=unifi
      - INFLUXDB_ADMIN_PASSWORD=unifi
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  up_grafana:
#    container_name: up_grafana
    image: grafana/grafana
#    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
    #  - /mnt/iscsi/docker/up_grafana:/var/lib/grafana
      - data:/var/lib/grafana  
      - /mnt/iscsi/docker/gf_provsioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
      - UP_INFLUXDB_URL=http://{{.Node.Hostname}}.mydomain.com:8086

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  un-poller:
#    container_name: up-poller
#    restart: unless-stopped
    image: golift/unifi-poller:latest
    depends_on:
      - influxdb
      - grafana
    environment:
      - UP_UNIFI_DEFAULT_URL=https://192.168.1.1
      - UP_UNIFI_DEFAULT_USER=<redacted>
      - UP_UNIFI_DEFAULT_PASS=<redacted>
      - UP_UNIFI_DEFAULT_SAVE_SITES=true
      - UP_UNIFI_DEFAULT_SITE_0=default
      - UP_INFLUXDB_URL=http://{{.Node.Hostname}}.mydomain.com:8086
    volumes:
      - data:/config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  data:
    driver: gluster-vol1
 ```   
tl;dr it worked - the dir didn't exist and it was created with stackname_data
the only thing i can think of that would improve this aspect is it possibly creating one of the following structures instead of munging every services data into one folder 

 1. stackname_data\servicename
 2. stackname_service_data
 3. other logical variations on this theme as you see fit.

second issue:
the driver didnt show up here, not sure why, this would give folks ability to create volumes  as they see fit, if needed
![image](https://user-images.githubusercontent.com/11369180/152903909-1c8fa63e-2203-4de3-a799-624436893b1a.png)

but overall it seems to work, first time!

**Comment by scyto** [comment]
hmm well i just realized i can do this for the subdir issue
```
volumes:
  influxdb:
    driver: gluster-vol1
  grafana:
    driver: gluster-vol1
  poller:
    driver: gluster-vol1
  ```  

but i don't think i should have, this looks bad :-)

![image](https://user-images.githubusercontent.com/11369180/152904392-3cd64e90-5bf4-47fc-b5d1-33c3f889ff6d.png)

oddly the containers work just fine, i think the one with the coredump might have failed initial provisioning - not sure if thats related or not
